=== MistyProphet/XWSBezbednost/XMLProject/WEB-INF/scheme/racuni_banaka.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:cmn="http://www.project.com/common_types">

    <xs:import namespace="http://www.project.com/common_types" schemaLocation="common_types.xsd"/>
    <xs:element name="racuni_banaka">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kod_banke" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="racun_banke" type="cmn:TBroj_Racuna_Banke"/>
                            <xs:element name="id">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="naziv" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="swift">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[A-Z]{6}[0-9]{2}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MistyProphet/XWSBezbednost/XMLProject/bin/resource/banke.xml
<?xml version="1.0" encoding="UTF-8"?>
<racuni_banaka xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/Geek/Documents/XWSBezbednost/XMLProject/WEB-INF/scheme/racuni_banaka.xsd">
    <kod_banke swift='AAAARS01'>
        <racun_banke>111-1231231231231-32</racun_banke>
        <id>001</id>
        <naziv>A Banka</naziv>
    </kod_banke>
    <kod_banke swift='BBBBRS01'>
        <racun_banke>111-1231555551231-32</racun_banke>
        <id>002</id>
        <naziv>B Banka</naziv>
    </kod_banke>
    <kod_banke swift='CCCCRS01'>
        <racun_banke>111-1231266661231-32</racun_banke>
        <id>003</id>
        <naziv>C Banka</naziv>
    </kod_banke>
</racuni_banaka>
